version: '3.4'
services:
  db:
    image: postgres:9.5
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dockerinit/init.sql:/docker-entrypoint-initdb.d/init.sql
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres 

  redis:
    image: redis:5.0.7

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/leadona

  sidekiq:
    build:
      context: .
    depends_on:
      - web
      - db
      - redis
    volumes:
      - .:/leadona
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./dockerinit/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules: